@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Mar 24 08:42:54 +0800 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 6c4c184bd66745e1a7b71adee7027e2d --incr --debug typical --relax --mt 2 -L gtwizard_ultrascale_v1_7_6 -L xil_defaultlib -L cmac_usplus_v2_6_0 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cmac_usplus_0_exdes_tb_behav xil_defaultlib.cmac_usplus_0_exdes_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 6c4c184bd66745e1a7b71adee7027e2d --incr --debug typical --relax --mt 2 -L gtwizard_ultrascale_v1_7_6 -L xil_defaultlib -L cmac_usplus_v2_6_0 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cmac_usplus_0_exdes_tb_behav xil_defaultlib.cmac_usplus_0_exdes_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
